name: eventlogtester

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get -y install libefivar-dev pylint python3-pip tpm2-tools black isort
      - run: sudo pip3 install pyright yq

      # syntax checking: black
      - name: Run black
        run: black --check eventlog/eventlog.py

      # syntax checking: isort
      - name: Run isort
        run: isort --check-only eventlog/eventlog.py

      # syntax checking: pylint
      - name: Run pylint (static analysis)
        run: pylint --rcfile pylintrc eventlog/eventlog.py
      
      # type checking: pyright (checking type hints)
      - name: Run pyright (checking type hints)
        run: pyright

      # good log testing: run event log validation (check event log consistency)
      - name: Run event log validation
        run: env PATH=${PATH}:${PWD}/testing PYTHONPATH=${PWD} validate_good_logs.py -d ${PWD}/testing/good_logs

      # good log testing: comparisons with tpm2-tools output
      - name: Run comparisons with tpm2-tools output
        run: env PATH=${PATH}:${PWD}/testing PYTHONPATH=${PWD} test_good_logs.py -d ${PWD}/testing/good_logs

      # good log testing: comparisons with tpm2-tools output generated PCR values
      - name: run comparisons with tpm2-tools output for expected PCR values
        run: env PATH=${PATH}:${PWD}/testing PYTHONPATH=${PWD} validate_pcrs.py -d ${PWD}/testing/good_logs
