name: eventlogtester

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get -y install libefivar-dev pylint python3-pip tpm2-tools black isort
      - run: sudo pip3 install pyright yq

      # syntax checking: black
      - name: Run black
        run: black --check eventlog/eventlog.py

      # syntax checking: isort
      - name: Run isort
        run: isort --check-only eventlog/eventlog.py

      # syntax checking: pylint
      - name: Run pylint (static analysis)
        run: pylint --rcfile pylintrc eventlog/eventlog.py
      
      # type checking: pyright (checking type hints)
      - name: Run pyright (checking type hints)
        run: pyright

      # step 3: run event log validation (check event log consistency)
      - name: Run event log validation
        run: true

      # step 4: run comparisons with tpm2-tools output
      - name: Run comparisons with tpm2-tools output
        run: true
